CREATE TABLE IF NOT EXISTS quality_reports(
  id INTEGER PRIMARY KEY,
  contentItemId INTEGER NOT NULL REFERENCES content_items(id) ON DELETE CASCADE,
  passed INTEGER NOT NULL DEFAULT 1,
  safetyScore INTEGER NOT NULL DEFAULT 100,
  checksJson TEXT NOT NULL DEFAULT '[]',
  createdAt TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS publishing_schedules(
  id INTEGER PRIMARY KEY,
  ownerId INTEGER NOT NULL REFERENCES users(id),
  brandId INTEGER NOT NULL REFERENCES brands(id),
  contentItemId INTEGER NOT NULL REFERENCES content_items(id) ON DELETE CASCADE,
  platform TEXT NOT NULL, -- 'YOUTUBE', 'INSTAGRAM', 'TIKTOK'
  scheduledAt TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'SCHEDULED', -- 'SCHEDULED', 'PUBLISHED', 'CANCELLED'
  customTitle TEXT,
  customCaption TEXT,
  customHashtags TEXT DEFAULT '[]',
  createdAt TEXT DEFAULT CURRENT_TIMESTAMP
);
